spring:
  datasource:
    url: jdbc:postgresql://18.117.117.125:5432/community
    username: ontheit
    password: gustjd12@
    driver-class-name: org.postgresql.Driver

MALE_HOST: smtp.gmail.com
MALE_PORT: 587
MALE_USERNAME: tlswlfk@gmail.com
MALE_PASSWORD: prlmoepesmdmmdhq