spring:
  datasource:
    url: jdbc:postgresql://18.119.124.137:5432/ontheit
    username: ontheit
    password: andcl12@
    driver-class-name: org.postgresql.Driver

MALE_HOST: smtp.gmail.com
MALE_PORT: 587
MALE_USERNAME: tlswlfk@gmail.com
MALE_PASSWORD: prlmoepesmdmmdhq