server:
  port: 8080


spring:
  profiles:
    active: dev
  data:
    redis:
      port: 6379
      password: ""
      host: 127.0.0.1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret:
    key: mysecretkeymysecretkeymysecretkeymysecretkey

