spring:
  datasource:
    url: jdbc:postgresql://18.189.11.17:5432/community
    username: ontheit
    password: gustjd12@
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      port: 6379
      password: ""
      host: 18.189.11.17
server:
  port: 8080
  address: 0.0.0.0

MALE_HOST: smtp.gmail.com
MALE_PORT: 587
MALE_USERNAME: tlswlfk@gmail.com
MALE_PASSWORD: prlmoepesmdmmdhq

