server:
  port: 8080


spring:
  profiles:
    active: prod
  data:
    redis:
      port: 6379
      password: ""
      host: 127.0.0.1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

S3:
  bucket:
    name: ontheit-image


jwt:
  secret:
    key: mysecretkeymysecretkeymysecretkeymysecretkey

