spring:
  datasource:
    url: jdbc:postgresql://18.189.11.17:5432/community
    username: ontheit
    password: gustjd12@
    driver-class-name: org.postgresql.Driver
server:
  port: 433
  address: www.ontheit.site

MALE_HOST: smtp.gmail.com
MALE_PORT: 587
MALE_USERNAME: tlswlfk@gmail.com
MALE_PASSWORD: prlmoepesmdmmdhq

